### ISSUE TITLE
Cannot call abstract method Spatie\Csp\Policies\Policy::configure()

### ISSUE THREAD

**Issue by Cannonb4ll** [spatie/laravel-csp#12]
I have tried creating a custom policy class following your guide, which is as follows:

```php
namespace App\Services\Csp;

use Spatie\Csp\Directive;
use Spatie\Csp\Policies\Policy;

class AppPolicy extends Policy
{
    public function configure()
    {
        parent::configure();

        $this->addDirective(Directive::SCRIPT, 'www.google.com');
    }
}
```

Also updated the csp.php config file:

```php
    /*
     * A policy will determine which CSP headers will be set. A valid CSP policy is
     * any class that extends `Spatie\Csp\Policies\Policy`
     */
    'policy' => App\Services\Csp\AppPolicy::class,
```

Also updated the Kernel.php to register the middleware:

```php
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
            \Spatie\Csp\AddCspHeaders::class,
        ],
```

But now im getting the error:

```
Cannot call abstract method Spatie\Csp\Policies\Policy::configure()
```

What am I doing wrong?

**Comment by faabsen** [comment]
I think the documentation is incorrect here: as you define your own new `AppPolicy` by extending it from the `Policy`, there is no need to call `parent::configure()`. Just delete this line and you are fine.

The documentation is defining a `Basic` policy and then referring to. However, this should be not `Policy` but `Basic` in my opinion.

**Comment by Cannonb4ll** [comment]
I see indeed, removing the `parent::configure()` solves this issue. I'll leave it open for the creators to respond.

**Comment by freekmurze** [comment]
Fixed it in the docs. My apologies for the troubles caused by this.
