### ISSUE TITLE
Question about min PHP version

### ISSUE THREAD

**Issue by olafnorge** [spatie/laravel-csp#19]
Hi,

I wanted to try out your package in my Laravel 5.5 application and tried to `composer require` it. But unfortunately it fails with non-matching dependencies.

A quick look into the `composer.json` of your package showed me, that the minimum PHP requirement is `7.1`. I am using `7.0` on my production server which comes with Ubuntu 16.04 LTS. Is there any reason why you are expecting PHP 7.1 (beside that its newer)?

Cheers,
Volker

**Comment by freekmurze** [comment]
Feel free to send a PR that adds compatibility for PHP 7.
