### ISSUE TITLE
cspNonce Inconsistent Rendering Behaviour in Blade Templates

### ISSUE THREAD

**Issue by Lymelight** [spatie/laravel-csp#22]
Hi,

Using laravel-csp in Laravel 5.5, Laravel Spark 5, I've noticed a strange issue cropping up while using the default configurations laid out in the documentation with regard to nonces - namely:

When nonces are rendered as the nonce attribute in the blade.php templates on script elements as documented: 

`<script defer src="/js/welcome.js" nonce="{{ cspNonce() }}"></script>`

**and no policy directives are set** (i.e. I am simply using a policy that extends `Spatie\Csp\Policies\Policy`, and returns `$this` in the `configure` method, rather than extending the provided Basic policy, with the predefined directives), a nonce attribute correctly displays on the page for each script element where directed after page load, like so:

`<script defer src="/js/welcome.js" nonce="pRgvQkQxaBLvkQWNCenZ5AqEuckPNyFZ"></script>`

In this example, however, the nonce is not actually being sent in the CSP header. As soon as I call *any* policy directive at all, whether this is extending the Basic Policy, or including any other `addDirective` statement (related to script-src, or any other CSP directive), or even just the `addNonceForDirective` method, the rendering of the nonce on the page is immediately prevented on script elements, and instead, it appears as though the attribute is empty, like so:

`<script defer src="/js/welcome.js" nonce></script>`

This does not preclude the nonce from actually being rendered on the page - it's still in the header, which appears like so:

`content-security-policy-report-only: script-src 'nonce-IT4hmF1IMJvpGmEFAb3yo15s9U180tdl'`

The nonce can be inserted via the `cspNonce` method into other element attributes on the page, for example a meta tag's content attribute:

`<meta name="csp-nonce" content="pRgvQkQxaBLvkQWNCenZ5AqEuckPNyFZ">`

It just can't seem to be inserted into a script or style tag, where it needs to be. Essentially, the only chained method that seems to be able to returned from `configure` in a policy without breaking the render of the nonce attribute on script or style elements is `reportOnly`.

Of course, not having a nonce in the inline scripts but having one added to, and then enforcing, the script-src directive will produce this error in the console:

`[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'nonce-pRgvQkQxaBLvkQWNCenZ5AqEuckPNyFZ'". Either the 'unsafe-inline' keyword, a hash ('sha256-IZ83MfjZbII/mkWsjjJ822079zcr7sBAEGI0rewq7lQ='), or a nonce ('nonce-...') is required to enable inline execution.`

and then adding the suggested 'unsafe-inline' to the script-src directive will produce the error,

`[Report Only] Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'nonce-pRgvQkQxaBLvkQWNCenZ5AqEuckPNyFZ' 'unsafe-inline' 'unsafe-eval'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.`

Those errors seem like consistent and expected behaviour from just enforcing the script-src directive, but I'm not entirely sure why the rendering of the nonce in the necessary elements breaks, or what I can do to prevent it - whether it's a quirk of my implementation, or some undocumented change was made that requires an additional step to make this work. Any suggestions would be appreciated.

**Comment by TVke** [comment]
Hi @Lymelight 

To start thank you for the extensive description of the problem. 
The first thing I need to point out is that when you are not using an inline script the `nonce` is not necessary. In your case a `$this->addDirective(Directive::SCRIPT,'self')` would work just fine. The other thing I need to point out that I would recommend extending from the base profile as it insures a basic security (like the `form-action` directive which needs to be set explicit and the `base-uri` directive that would render all the 'self' values useless). 
The thing is I found out that the problem you described is a chrome only problem it will not show the nonce in the body. But I thought I read somewhere that it was done on purpose to not expose the token the error can also be from injected scripts by adBlockers or other extensions. 

Hope this helps.
