### ISSUE TITLE
Inline Dom Events

### ISSUE THREAD

**Issue by yilmazerhakan** [spatie/laravel-csp#24]
Hi, 

Thanks for great packages, i should send you a lot of cards from my town.
I have an question/problem.

How can i add 'nonce' directive for this sample code,

`onclick="event.preventDefault(); document.getElementById('logout-form').submit();"`

Thanks...

**Comment by TVke** [comment]
Hi @yilmazerhakan 

inline event-listeners do not work with nonce tags because nonce is ment for block of JS code. 
Your two options are:
 1. add an eventListener in your JS code
 2. add `unsafe-inline` to your CSP profile (`addDirective(Directive::SCRIPT, 'unsafe-inline')`)
