### ISSUE TITLE
specialDirectiveValues are not constants

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-csp#25]
Cause of the fact that they are static/unchangeable and are used in a mapping to compare them they should be available as constants on the `Directive` class.

**Comment by Gummibeer** [comment]
Hey @TVke 

that's right - wasn't sure if adding a new class would be good. But yes, it reads better and is shorter!
Will do this later. :)

**Comment by freekmurze** [comment]
Fix in master.
