### ISSUE TITLE
cspNonce does not follow laravel function naming

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-csp#29]
The `cspNonce` helper function does not follow the normale laravel/php naming (snake_case). But this would be a BC.

**Comment by freekmurze** [comment]
I'd accept a PR that adds the `csp_nonce` function to the makes and marks the `cspNonce` function as deprecated.

**Comment by Jamesking56** [comment]
Isn't this issue closed by #30?

**Comment by TVke** [comment]
@Jamesking56 

that is correct, thank you for letting us know.
