### ISSUE TITLE
[Feature] Automatic apexes inclusion for hashes

### ISSUE THREAD

**Issue by IlCallo** [spatie/laravel-csp#33]
Let apart nonces, another possibility for CSP 2 onward are base64 encoded hashes.
They can be useful when you are lazy loading scripts from your code base, because you cannot attach them the same nonce of the first page load of course.
Actually it's possible to just set them as

    $this->addDirective(Directive::STYLE, '\'sha256-K28TraF0hDSDYoxDYfyCCb5cCVAhDUyT0P1E3a+hKyQ=\'');

which is pretty awful because you must remember to enclose them into apexes like other special values.

It could be useful to take away the hassle from the developer and make the library manage it.
I was thinking something like an hash autodetection, given the fact that all hashes contain the hashing algoritm as a prefix.

Do you like the idea?
I can add it with a `isHash()` method called into `sanitizeValue`, in Policy abstract class.

**Comment by freekmurze** [comment]
If the code required to add this is simple, well tested and documented I'd consider accepting a PR for this.
