### ISSUE TITLE
[Feature] HSTS, HPKP and other security headers

### ISSUE THREAD

**Issue by IlCallo** [spatie/laravel-csp#34]
Some other [packages](https://github.com/aidantwoods/SecureHeaders) manage, together with CSP, also others security headers putting some helpful defaults.
Do you like the idea of adding these kind of defaults on this package or you think to this package as only-CSP?

If it's the latter, do you mind if I build a package using yours and the others to get the best of all packages?

**Comment by freekmurze** [comment]
I'd like to only focus on csp right now.

Feel free to require our package or use our code to build yours.

**Comment by BePsvPT** [comment]
@IlCallo hi,

I have already created a package that may meet your needs, https://github.com/BePsvPT/secure-headers, hope this will help you.
