### ISSUE TITLE
Please, write "work on php version > 5.6"

### ISSUE THREAD

**Issue by gimtonic** [spatie/laravel-csp#37]
Please, write "work on php version > 5.6"

**Comment by gimtonic** [comment]
Write in README.MD

**Comment by Gummibeer** [comment]
How could/should this package work on PHP5.6 if it uses PHP7 scalar type-hints!?

**Comment by sebastiandedeyne** [comment]
@gimtonic Version constraints are always explicitly set in the `composer.json` file, I'd suggest you always check there when looking into a new package. This is also a safer place to look because readme's aren't always up to date :)
