### ISSUE TITLE
vuejs doesn't work without unsafe-eval in Directive::SCRIPT

### ISSUE THREAD

**Issue by hhummell81** [spatie/laravel-csp#40]
Hi!

I know this is not a issue of this package, but as far I can see is impossible to enable CSP with vuejs as the default way that Laravel provides, without enabling unsafe-eval inside Directive::SCRIPT, what is a security risk.

Is there any configuration to allow using the default vuejs that Laravel provides?

Steps to reproduce:

- Clean install of Laravel (5.6).
- Install spatie csp package. Add id="app" in main div inside body.
- Compile npm run prod and there is nothing inside body.
- If unsafe-eval added to Directive::SCRIPT, all shows up.

Thanks!

**Comment by Gummibeer** [comment]
I would try to add nonce to the script tags. This will prevent you from enable all inline script tags.

**Comment by hhummell81** [comment]
Thanks @Gummibeer !

The issue is that even with nonce tags, I don't have a script tag where add it to. Vuejs just takes the #app div and works with it, so there is no inline script added nowhere. Maybe I am missing something?

**Comment by hhummell81** [comment]
When I disable unsafe-eval, it just dissapear the content with no warning at all. The last thing, use the runtime build of vue, is what I was trying to use with no success, but probably is because I don't know how to configure webpack in the right way.

Thanks!

**Comment by Gummibeer** [comment]
I would recommend you to ask this question at VueJS https://github.com/vuejs/vue - this is more about VueJS & CSP in general than this package.
So I bet that they can answer your question in a better way.

There are also several issues related to CSP already: https://github.com/vuejs/vue/issues?utf8=%E2%9C%93&q=is%3Aissue+csp

**Comment by RGENT** [comment]
@hhummell81 

VueJS has 2 different versions: the full version and the runtime version.  'unsafe-eval' is only needed for the full version of VueJS; the runtime version doesn't need it.

Generally, you'll need the full version if you are compiling templates that are loaded from the site.  E.g., you have a CMS that serves up articles that have Vue components embedded in them.  For most cases, you should be able to get away with the runtime version.

**Comment by hhummell81** [comment]
@RGENT it is clear that is the solution. I still looking at how implement it with the default vuejs implementation in laravel (I don't want to make a SPA for instance, rendering just the root component).

I am going to close this issue, if someone implements it with the default way Laravel is using vuejs, please open it again and tell us how you did it.

Thanks to all!

P.S.: By the way, this is a great package. It would improve security in all sites, without looking if CSP is also configured in the webserver. Thanks for your great job!
