### ISSUE TITLE
Boolean Directives Cannot Have Empty Value

### ISSUE THREAD

**Issue by gabe565** [spatie/laravel-csp#43]
Hello!

Loving this middleware so far, but I have found a problem. Some CSP directives (such as `upgrade-insecure-requests`, `block-all-mixed-content`, `disown-opener`, and `sandbox`) either do not allow or do not always require a value.

With the current method of adding directives, this is not possible.
Could this be modified so that the second value is optional with these directives?

Thank you!

**Comment by freekmurze** [comment]
I'd accept a PR that adds this to the package. Be sure to add tests and an updated readme.

**Comment by tomhatzer** [comment]
@freekmurze Can you please have a look at the PR and tell me if that's ok?

**Comment by freekmurze** [comment]
Seems good on first sight, thank you!

I'll do a thorough review later this week.
