### ISSUE TITLE
Add support for Feature-Policy

### ISSUE THREAD

**Issue by Gummibeer** [spatie/laravel-csp#45]
There is a new header `Feature-Policy` very similar to the CSP one. Because of some overlapping constants it could be an idea to add this header to this library!?

**sources:**
* https://wicg.github.io/feature-policy/
* https://developers.google.com/web/updates/2018/06/feature-policy
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy
* https://scotthelme.co.uk/a-new-security-header-feature-policy/

**Comment by freekmurze** [comment]
I'm thinking that a separate package would be better. Currently have no intentions of growing this to a full blow security headers package. Feel free to fork our code to create a package of your own for that header.
