### ISSUE TITLE
EvalError: call to Function() blocked by CSP

### ISSUE THREAD

**Issue by iarif4u** [spatie/laravel-csp#56]
When i call CDN 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js'
then i get the message "EvalError: call to Function() blocked by CSP"

**Comment by Gummibeer** [comment]
Hey, have you allowed `unsafe-eval` in your CSP? 

https://stackoverflow.com/questions/10944794/csp-how-to-allow-unsafe-eval-for-a-given-uri-prefix-firefox
