### ISSUE TITLE
is it possible to override a CSP that is set at the nginx level?

### ISSUE THREAD

**Issue by vesper8** [spatie/laravel-csp#62]
On one of my client's projects there is a line in the nginx config that adds

```
content-security-policy: frame-ancestors 'self'
```

I used this package here to add
```
content-security-policy: frame-ancestors https://example.com
```

But I am still unable to load content from an iframe because the error is quoting that the frame-ancestors policy is set to 'self'

In the response headers I can clearly see that both rules are there.. but I guess the first one takes precedence.. is there no way to override it? Is the only solution to somehow modify the nginx config at the server level?

**Comment by Gummibeer** [comment]
That's a "problem" with nginx. You will have to tell nginx to add the header only if it's not already set by the proxy process.
There is nothing this package, laravel or php could do to prevent nginx from adding an already set header.

**Comment by vesper8** [comment]
I completely understand there's no way to prevent Nginx from adding it without changing the configuration directly, the question was is there not a way to override an already-set CSP, for example replace it, or append to it in such a way that it no longer only allows 'self' but also allows a domain I specify.

**Comment by Gummibeer** [comment]
You can drop the nginx and add self to the PHP CSP.
But nginx and php-fpm are decoupled processes. And nginx can work with the php-fpm response but php-fpm can't control nginx or interact with it (without modules or custom code or other hacks).

I've removed every nginx headers and let Laravel handle all of them.
