### ISSUE TITLE
include support for require-trusted-types-for

### ISSUE THREAD

**Issue by m1stermanager** [spatie/laravel-csp#66]
When I attempted to feed our CSP into the google evaluator at https://csp-evaluator.withgoogle.com/ it told me I may want to include `require-trusted-types-for 'script'`. When I attempt to include that directive it is flagged as invalid by the base Policy (via the Directive class)

This is way low priority as this appears to be a very new directive and support for it (or even evidence of its existence outside of some google engineering resources) seem spotty? Its only barely mentioned on MDN (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#Other_directives) but does not even get its own page...

If you would like to include this, I'll absolutely 100% open a PR for it, if you want to wait until that directive is a bit more "legit" I totally get that.

**Comment by freekmurze** [comment]
Thanks for your proposal, let's wait until the directive has some more traction.
