### ISSUE TITLE
Missing keyword data:

### ISSUE THREAD

**Issue by neterjan** [spatie/laravel-csp#69]
Personlly, I am missing Keyword for data:.
Found sollution here: https://stackoverflow.com/questions/18447970/content-security-policy-data-not-working-for-base64-images-in-chrome-28

**Comment by Gummibeer** [comment]
Hey,
Like I've explained in #63 it's not a keyword but a scheme and implemented as such.

**Comment by neterjan** [comment]
Wow, thank you. Great plugin
