### ISSUE TITLE
Feature: disable CSP for certain routes

### ISSUE THREAD

**Issue by matthijs** [spatie/laravel-csp#72]
Hi,

I would like to disable the CSP for certain routes. I have a case where I use a javascript library on a certain page which does not play nice with the CSP.

Currently I override the shouldBeApplied() function in my policy class and add an exception for the route. I'd rather have it in the middleware like 'VerifyCsrfToken' does. It seems to me a more logical place then the Policy class itself.

Regards, Matthijs

**Comment by Gummibeer** [comment]
Hey,

you can use the `shouldBeApplied()` method for this.
```php
public function shouldBeApplied(Request $request, Response $response): bool
{
    return config('csp.enabled') && empty($response->exception);
}
```
I'm excluding all exception responses for example because they are rendered by Ignition and I don't want to allow all ignition resources.

**Comment by matthijs** [comment]
Yes, I know I can use the `shouldBeApplied()` function but its here more a bit of a design question I think.

Now I need for every seperate policy an `shouldBeApplied()` function while I could solve it in the Middleware. The actual question is then: is the policy class responsible for applying it to certain routes? In my opinion the policy class is solely responsible for building up the policy and that the Middleware should apply the policy if applicable.

Its more a design question, but its up to @freekmurze to have an opinion on this.

**Comment by freekmurze** [comment]
I don't have a strong opinion on that. Personally I think checking it in the policy class is good enough.

If you want to do it some other way you could create a class that does the check and call that class from the policy.
