### ISSUE TITLE
Error installl in laravel 5.6

### ISSUE THREAD

**Issue by agenciatamandua** [spatie/laravel-csp#80]
I'm trying to execute the command:

composer require spatie/laravel-csp

and i am receiving a error:
![error](https://user-images.githubusercontent.com/49321514/101530922-53814300-3971-11eb-8829-577c5cc09c1d.jpg)

**Comment by freekmurze** [comment]
Please make sure you meet all requirements to install the package.

**Comment by agenciatamandua** [comment]
could at least indicate the requirements not found on your page

**Comment by Gummibeer** [comment]
Check the composer.json or packagist page which lists the requirements for all versions.
