### ISSUE TITLE
Config file can't be published with --tag=config (2.7.0)

### ISSUE THREAD

**Issue by mortenscheel** [spatie/laravel-csp#86]
According to the installation guide, the config file can be published by running
```shell
php artisan vendor:publish --provider="Spatie\Csp\CspServiceProvider" --tag="config"
```
Which just prints the warning `No publishable resources for tag [config]`.
The config file can be published by running the command without `--tag="config"`.

**Comment by jfrosorio** [comment]
Having the same problem...
